'use strict';

const readline = require('readline');

function ask(question, defaultValue = '') {
  return new Promise((resolve) => {
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    });
    const prompt = defaultValue ? `${question} [${defaultValue}]: ` : `${question}: `;
    rl.question(prompt, (answer) => {
      rl.close();
      resolve(answer.trim() || defaultValue);
    });
  });
}

async function runWizard() {
  console.log('\n=== AI Alias System — Project Setup Wizard ===\n');
  console.log('This wizard creates your project-aliases.md template.\n');

  const projectName = await ask('Project name');
  const projectDesc = await ask('Project description');

  console.log('\n--- @ Projects (repositories / packages) ---');
  console.log('Enter project aliases. Press Enter with empty name to stop.\n');

  const projects = [];
  while (true) {
    const alias = await ask('Alias (e.g. @API)');
    if (!alias) break;
    const repoPath = await ask('Repo / Path (e.g. packages/api/)');
    const description = await ask('Description');
    projects.push({ alias, repoPath, description });
  }

  console.log('\n--- $ External Services ---');
  const services = [];
  while (true) {
    const alias = await ask('Alias (e.g. $Stripe)');
    if (!alias) break;
    const service = await ask('Service name');
    const notes = await ask('Notes');
    services.push({ alias, service, notes });
  }

  console.log('\n--- # Topics / Workstreams ---');
  const topics = [];
  while (true) {
    const alias = await ask('Alias (e.g. #Auth)');
    if (!alias) break;
    const scope = await ask('Scope / description');
    topics.push({ alias, scope });
  }

  return buildAliasMarkdown({ projectName, projectDesc, projects, services, topics });
}

function buildAliasMarkdown({ projectName, projectDesc, projects, services, topics }) {
  const lines = [];

  lines.push(`# Project Aliases — ${projectName}`);
  if (projectDesc) lines.push(`\n> ${projectDesc}`);
  lines.push('\n> Generated by ai-alias-system. Edit freely.\n');
  lines.push('---\n');
  lines.push('## Symbol Legend\n');
  lines.push('```');
  lines.push('@  = project/repo/sub-package');
  lines.push('$  = external service/client');
  lines.push('#  = topic/workstream/feature area');
  lines.push('&  = team/role/domain');
  lines.push('%  = asset/resource/data store');
  lines.push('~  = agent/bot/automated system');
  lines.push('```\n');
  lines.push('---\n');

  if (projects.length) {
    lines.push('## @ Projects\n');
    lines.push('| Alias | Repo / Path | Description | Visibility |');
    lines.push('|-------|-------------|-------------|------------|');
    for (const p of projects) {
      lines.push(`| ${p.alias} | ${p.repoPath} | ${p.description} | Private |`);
    }
    lines.push('');
  }

  if (services.length) {
    lines.push('## $ External Services\n');
    lines.push('| Alias | Service | Notes |');
    lines.push('|-------|---------|-------|');
    for (const s of services) {
      lines.push(`| ${s.alias} | ${s.service} | ${s.notes} |`);
    }
    lines.push('');
  }

  if (topics.length) {
    lines.push('## # Topics / Workstreams\n');
    lines.push('| Alias | Scope |');
    lines.push('|-------|-------|');
    for (const t of topics) {
      lines.push(`| ${t.alias} | ${t.scope} |`);
    }
    lines.push('');
  }

  lines.push('## & Teams / Roles\n');
  lines.push('| Alias | Scope |');
  lines.push('|-------|-------|');
  lines.push('| &Backend | API, database, infra |');
  lines.push('| &Frontend | Web, mobile, UI |');
  lines.push('');

  lines.push('## % Assets / Resources\n');
  lines.push('| Alias | Location / Service |');
  lines.push('|-------|--------------------|');
  lines.push('| %DB | [Your database] |');
  lines.push('');

  lines.push('## ~ Agents / Bots\n');
  lines.push('| Alias | Purpose |');
  lines.push('|-------|---------|');
  lines.push('| ~QAAgent | Typecheck + tests |');

  return lines.join('\n');
}

module.exports = { runWizard, buildAliasMarkdown, ask };
